Endpoint Realizar Transferencia Feature/us 170
abelardog/Skill-Up-C1 pull request #49
Opened 2022-11-06 22:32 UTC by lidioguedez

SUMMARY
* Created Transfer Endpoint
* Create service method for transfer
* Fixes
![image](https://user-images.githubusercontent.com/112365426/200198790-94668499-b2e3-41a9-acfd-f840245ac4fa.png)

![image](https://user-images.githubusercontent.com/112365426/200198803-170b2570-2906-48ce-87e3-f844d9306426.png)

2022-11-06 22:34 UTC, lidioguedez commented
Aun no esta completo pero lo subi para ver como voy si debo cambiar algo o esta todo mal. Mas tarde reviso lo que me corrijan

2022-11-07 13:35 UTC, DiegoCat1989 commented
Hay una clase AccountsRepository, ¿dejamos de usar el GenericRepository?

2022-11-07 14:56 UTC, lidioguedez commented
> 

No el AccountRepository hereda del repo generico solo que necesitaba elgun metodo espesifico en el servicio y asi se soluciona.

2022-11-07 17:14 UTC, duncan077 requested changes
En el servicio, traes al usuario con la informacion del token y luego estas trayendolo devuelta con la misma informacion. Lo que tenes que hacer es traer el account con el id del request que es el Id que pasas como parametro a la funcion. Y luego haces el if account.userid==user.userid todo los demas sino throw.
Lo demas creo que esta bien

2022-11-07 18:55 UTC, lidioguedez commented
> En el servicio, traes al usuario con la informacion del token y luego estas trayendolo devuelta con la misma informacion. Lo que tenes que hacer es traer el account con el id del request que es el Id que pasas como parametro a la funcion. Y luego haces el if account.userid==user.userid todo los demas sino throw. Lo demas creo que esta bien

Listo

2022-11-07 19:11 UTC, duncan077 commented
> > En el servicio, traes al usuario con la informacion del token y luego estas trayendolo devuelta con la misma informacion. Lo que tenes que hacer es traer el account con el id del request que es el Id que pasas como parametro a la funcion. Y luego haces el if account.userid==user.userid todo los demas sino throw. Lo demas creo que esta bien
> 
Perfecto lo unico que te pido es que vuelvas a poner el di del mapper ya que lo estoy usando en listedaccounts

2022-11-08 01:42 UTC, lidioguedez commented
> > > En el servicio, traes al usuario con la informacion del token y luego estas trayendolo devuelta con la misma informacion. Lo que tenes que hacer es traer el account con el id del request que es el Id que pasas como parametro a la funcion. Y luego haces el if account.userid==user.userid todo los demas sino throw. Lo demas creo que esta bien
> 
> Perfecto lo unico que te pido es que vuelvas a poner el di del mapper ya que lo estoy usando en listedaccounts

LIsto

2022-11-08 01:42 UTC, duncan077 approved these changes

2022-11-08 01:42 UTC, merged