Feature/us128 Endpoint Eliminación de un User
abelardog/Skill-Up-C1 pull request #76
Opened 2022-11-09 16:47 UTC by braianvelarde

![imagen](https://user-images.githubusercontent.com/15269215/200890333-fc1a932a-92e0-44b5-b338-fab098b0de06.png)

2022-11-09 18:30 UTC, duncan077 requested changes
Habiamos quedado con el mentor en usar softdelete, en ves de borrarlo se hace un update al atributo IsDeleted = true

2022-11-09 19:43 UTC, braianvelarde commented
Es verdad, ahora lo cambio. Gracias

2022-11-10 17:19 UTC, lidioguedez approved these changes

2022-11-10 17:22 UTC, lidioguedez approved these changes

2022-11-10 18:20 UTC, duncan077 approved these changes

2022-11-10 18:20 UTC, merged