endpoind datos de usuario autenticado
abelardog/Skill-Up-C1 pull request #80
Opened 2022-11-10 01:40 UTC by pablodclavijo

![Captura de pantalla 2022-11-09 223653](https://user-images.githubusercontent.com/76256398/200979522-55c6f123-45da-4a1d-8887-d11858dc327c.png)

2022-11-10 18:03 UTC, duncan077 requested changes
Se refiere a los datos de la entidad usuario, y el usuario lo obtenes del header.

2022-11-10 18:42 UTC, pablodclavijo commented
> Se refiere a los datos de la entidad usuario, y el usuario lo obtenes del header.

con razón jaja me parecía demasiado simple

2022-11-10 19:44 UTC, duncan077 requested changes
Una ultima cosa y listo, te pido que uses un dto y dejes afuera IsDeleted y password
Y que no incluya las entidades, por ejemplo la lista de accounts. A menos que querias hacerlo, en cuyo caso creo que tenes q hacer un include.

2022-11-10 20:22 UTC, lidioguedez commented
UserDTO Ya existe solo usalo

2022-11-12 21:28 UTC, duncan077 approved these changes

2022-11-12 21:28 UTC, merged